name: ARC Developement Installer

on:
  workflow_dispatch:
    inputs:
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
      min:
        required: true
        type: number
      max:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: run the arc-dev-installer bash script
        run: /bin/bash -x arc-dev-installer.sh -token ${{ secrets.GITHUB_TOKEN }} -owner ${{ inputs.owner }} -repo ${{ inputs.repo }} -min ${{ inputs.min }} -max ${{ inputs.max }}
